export enum TypeNames {
  LOAD_ORDERS = 'MYOS/ORDER/LOAD',
  UPDATE_SINGLE_ORDER = 'MYOS/ORDER/UPDATE_SINGLE',
  LOAD_SINGLE_ORDER = 'MYOS/ORDER/LOAD_SINGLE',
  REMOVE_SINGLE_ORDER = 'MYOS/ORDER/REMOVE_SINGLE',
}