export enum TypeNames {
  LOAD_PRODUCTS = 'MYOS/PRODUCT/LOAD',
  UPDATE_SINGLE_PRODUCT = 'MYOS/PRODUCT/UPDATE_SINGLE',
  LOAD_SINGLE_PRODUCT = 'MYOS/PRODUCT/LOAD_SINGLE',
  REMOVE_SINGLE_PRODUCT = 'MYOS/PRODUCT/REMOVE_SINGLE',
}